apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    type: postgres
    app: myapp

spec:
  replicas: 1
  selector:
    matchLabels:
      type: postgres
      app: myapp
  template:
    metadata:
      name: postgres-pod
      labels:
        type: postgres
        app: myapp
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-configmap
