version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=automatyzacja
      - PORT=5000
    ports:
      - 5000
  mongodb:
    image: mongo:latest
    ports:
      - 27017

