# version: '3'

# services:
#   # backend:
#   #   build:
#   #     dockerfile: Dockerfile
#   #     context: ./server
#   #   environment:
#   #     - MONGO_HOST=localhost
#   #     - MONGO_PORT=27017
#   #     - MONGO_DATABASE=automatyzacja
#   #     - PORT=5000
#   #   ports:
#   #     - 5000
#   mongodb:
#     image: mongo:latest
#     ports:
#       - 27017


version: '3.7'
services:

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
      - ./postgres:/docker-entrypoint-initdb.d


  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8081:8080
    depends_on:
      - postgres
      
volumes:
  postgres:
