version: '3.7'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server-ps
    environment:
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
      - PG_HOST=127.0.0.1
      - PORT=5000
    ports:
      - 5000:5000
  
  # postgres:
  #   image: postgres:13.0-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DATABASE=postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #   - ./postgres://var/lib/postgresql/data
      # - postgres:/var/lib/postgres/data
      # - ./postgres:/docker-entrypoint-initdb.d



# version: '3.7'
# services:

  # keycloak:
  #   image: quay.io/keycloak/keycloak:15.0.2
  #   environment:
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: postgres
  #     DB_DATABASE: keycloak
  #     DB_USER: keycloak
  #     DB_SCHEMA: public
  #     DB_PASSWORD: password
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - postgres
      
# volumes:
#   postgres:
