apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
  labels:
    type: postgres
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    type: postgres
    app: myapp
